apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frontend:latest   # ✅ FIXED image name
        imagePullPolicy: Never
        ports:
        - containerPort: 80

        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
           memory: "128Mi"
           cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort   # ✅ CHANGE HERE
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007 # ✅ fixed port